services:
  db:
    image: public.ecr.aws/docker/library/postgres:15-alpine
    pull_policy: if_not_present
    container_name: spruzhuk_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: spruzhuk
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spruzhuk_net

  backend:
    image: spruzhyk-backend:latest
    container_name: spruzhuk_backend
    restart: unless-stopped
    environment:
      DB_USER: postgres
      DB_PASSWORD: rootpassword
      DB_NAME: spruzhuk
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
    networks:
      - spruzhuk_net

  frontend:
    image: spruzhyk-api:latest
    container_name: spruzhuk_app
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - spruzhuk_net

networks:
  spruzhuk_net:
    driver: bridge

volumes:
  postgres_data:
